---
dataShowcase:
    # The environment can be public or internal (restricted).
    environment: Public
    # Paths to the logos for Data showcase application to be overwritten by external config
    ntrLogo: 'default'
    vuLogo: 'default'

---
grails:
    profile: angular
    codegen:
        defaultPackage: nl.thehyve.datashowcase
    spring:
        transactionManagement:
            proxies: false
    gorm:
        failOnError: true
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        default:
            # Turn off automatic versioning and timestamping by GORM
            mapping:
                version: false
                autoTimestamp: false

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    resources:
        pattern: /**

---
grails:
    cors:
        enabled: false
environments:
    development:
        grails:
            cors:
                enabled: true
    developmentInternal:
        grails:
            cors:
                enabled: true
---
hibernate:
    show_sql: true
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: datashowcase
    password: datashowcase

environments:
    developmentInternal:
        dataShowcase:
            environment: Internal
    testInternal:
        dataShowcase:
            environment: Internal
---
grails:
  controllers:
      upload:
            maxFileSize: 50000000
            maxRequestSize: 50000000
---
grails:
  plugin:
    springsecurity:
      active: false
---
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/data_showcase
    developmentInternal:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/data_showcase
    test:
        dataSource:
            dbCreate: create
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            driverClassName: org.h2.Driver
            username: sa
            password: ''
    testInternal:
        dataSource:
            dbCreate: create
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            driverClassName: org.h2.Driver
            username: sa
            password: ''
    production:
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://localhost:5432/data_showcase
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

